// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PriceTracker.Data;

#nullable disable

namespace PriceTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624100142_AddPriceHistory2")]
    partial class AddPriceHistory2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PriceTracker.Models.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TrackedProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackedProductId");

                    b.ToTable("PriceHistory");
                });

            modelBuilder.Entity("PriceTracker.Models.TrackedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrackedProducts");
                });

            modelBuilder.Entity("PriceTracker.Models.PriceHistory", b =>
                {
                    b.HasOne("PriceTracker.Models.TrackedProduct", "TrackedProduct")
                        .WithMany("PriceHistory")
                        .HasForeignKey("TrackedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedProduct");
                });

            modelBuilder.Entity("PriceTracker.Models.TrackedProduct", b =>
                {
                    b.Navigation("PriceHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
